### ISSUE TITLE
Dependencies should have min version number in schema

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/Brochard#14]
At the moment when you add a project, you compile everything and load it... 

Lets say Project A have a version of 1.0.0.0 and Project B has a version of 2.0.0.0 and a dependency on Project A version 1.5.0.0, both will get built and then fall over.

What should happen is that Project B should not compile, and report a error in the log.

**Comment by Jetski5822** [comment]
Maybe change Dependencies from:

Dependencies: OrchardVNext.Test1

To

Dependencies:
    OrchardVNext.Test1:
        Version: 1.5.0.0

Or maybe something similar to the Nuget Spec? http://docs.nuget.org/create/nuspec-reference#specifying-dependencies but in YAML.

**Comment by bleroy** [comment]
Npm is another good reference for that sort of thing, but this is another case where a very deliberate choice was made for a problem that is known not to have a good solution. The good question to ask is, over those years of being relaxed about dependency versions, has this been an objective source of pain for our users, and if so, has it been more painful than the pain felt by members of other communities (Node or NuGet) that have made different choices? This is one of those things that look like a good idea, because as engineers we like to be in control. We should however look at the evidence.

**Comment by Jetski5822** [comment]
I think it has been a pain point for our users. You pull down a module without even knowing if its going to work, 50% of the time it feels like pot luck.

**Comment by bleroy** [comment]
Having min version numbers is not enough to solve that problem, unfortunately.

**Comment by Jetski5822** [comment]
The package specs should solve this for us without the need for any custom configuration. The only thing we should drop is Module Version from Module.txt as that now belongs in the project.json file.
