### ISSUE TITLE
Should Module.txt files change to be .nuspec files?

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/Brochard#15]
At the moment Module.txt is in the format defined by the Orchard team, but should we consider moving to the nuspec file format? Does the nuspec format provide the information re require?

**Comment by bleroy** [comment]
What would be the benefit? When we chose to use YAML for that file, that is going to be authored by human beings, we knew about XML and JSON. The reasons to use YAML then (human-writable) still stand today. It's trivial for a machine to make a XML file from the YAML manifest, so I really don't see what the benefit could possibly be.

Plus, as you point out, with our own format, we are free to extend it in however way we choose instead of having to depend on the NuGet maintainers.

**Comment by Jetski5822** [comment]
Okay, agreed. I would actually like the ability to support YAML, JSON, XML and any other format the configuration classes provide as first class citizens.

YAML support: https://github.com/aspnet/Configuration/issues/82
