### ISSUE TITLE
Split framework in to individual nuget packages

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/Brochard#17]
At the moment the framework is this big monolithic package. I think it should be split up, still have a framework package to pull things together, but things like DI, MVC, etc could be packaged off.

**Comment by Piedone** [comment]
Why?

**Comment by Piedone** [comment]
OMG, I'm turning into @bleroy . So: what do you think, what advantages would it bring to split Orchard.Framework into multiple chunks, when everything there is indeed framework functionality? This would mean that we'd have a lot of small projects that you'd need to separately reference (and remember to reference, and remember which one you need to reference for which functionality; what is especially hard if you're looking for extension methods). I see no advantages but a lot of issues.

**Comment by Jetski5822** [comment]
Splitting things up would allow projects outside of Orchard to opt in to specific parts of Orchard functionality. Yes Orchard.Framework is for Orchard, but when you take it, you take everything.

The framework has a lot of nice design components that other projects/cms's etc could benifit to use but in most cases they don't want to take everything. Remember the new asp.net model is an opt-in approach.

Orchard.Framework is kind of the our version of System.Web in my opinion (except nicer :))

**Comment by Piedone** [comment]
Well, with Orchard App Host projects outside Orchard take on Orchard.Framework at it never caused any issues that "everything" is in there. The only problem was with LocalizedStrings (see: https://github.com/OrchardCMS/Orchard/issues/4752) but that only arises when you actually want to use localization (and wouldn't be solved by splitting Orchard.Framework).

I hate to say this as I frequently come up with ideas rooted in theoretical concerns, but I think a change like this would bring purely theoretical advantages, but only disadvantages in practice. (Again, think about having to add all the references.)

Can you give specific examples where this would be better? I don't mean probable cases but real-world examples where the current approach prevents use of Orchard's features and a divided design would enable adoption.

**Comment by urbanit** [comment]
Not that matters, but imo Framework should be solid and not split. In other case, we need take care of what is dependent on and etc. Who needs that on this level?

**Comment by bleroy** [comment]
Single responsibility, ability to include bits of Orchard (or all of it) in
applications. On the downside, more assemblies is generally not good, but
packaging and design are two different things. A more rational
factorization of the code, based on function rather than how fundamental it
is, would benefit us. That's, by the way, what I did in DecentCMS: there's
a small replaceable server.js that bootstraps the system, and everything
else is factored into small services with a single responsibility. You can
package services into modules, and a set of modules into one folder (I have
a core folder that is the equivalent of Orchard's Fx + Core), but
everything is neatly uncoupled, and factored exactly right. Orchard is a
little messier in that it has three different kinds of services in Fx,
Core, and regular modules. I think it's a good idea to question that
organization.

**Comment by Piedone** [comment]
Yes, but Orchard.Framework is already designed with SRP in mind and there is no unnecessary coupling between its components (e.g. you don't need to do anything with MVC if you just want to use DI). Packaging it in the same way, however, would introduce a lot of complexity and practical downsides.

I don't think it's the same question just related on what to do with the different kind of modules, but I agree that having Core and standard modules, as well as Core modules in the Core project and in their own is confusing and we should do something about it.

**Comment by bleroy** [comment]
I don't think anyone is suggesting packaging along the same lines as component boundaries. I certainly am not. What I am suggesting is actually the opposite: make packaging decisions completely orthogonal to component boundaries. I would have a small amount of code to bootstrap the engine, then have everything else in modules that can be packaged anywhere: it shouldn't matter what dll or folder a module is in, and we might even have different dll distributions depending on the target. For example, there could be benefits in having all of the core distribution under a very small number of dlls (one?) on deployed instances. We already do things differently in precompiled packages, maybe we can push that further. When developing locally, we could have a smarter dynamic compilation system, now that Roslyn is here, that splits things up in module dlls like today, but without the waste and duplication we currently have in our module bin folders. Things are far from perfect today, and investigating how to make them better looks like a good idea.

**Comment by Piedone** [comment]
Ah, I see and I agree. This is similar to the idea of being able to basically build your own Orchard solution (which currently in the simplest case is removing modules that you don't need for example). However I don't think this is what @Jetski5822 is suggesting here.

**Comment by bleroy** [comment]
I'll let him clarify what he meant.

**Comment by jrestall** [comment]
I think this would provide a lot of benefit to the wider ASP.NET community if it was targeted as such. For years there have been efforts to make MVC support plugins and modularity E.g. [Portable Areas](http://jeffreypalermo.com/blog/mvccontrib-working-on-portable-areas/). Having the ability to bootstrap not just an orchard site, but any MVC site with a very good plugin system, localization, logging, DI etc could see a lot of usage and garner uptake and contribution to Orchard itself.   

Maybe we are talking about something like [HTML5 initializr](http://www.initializr.com/) but for ASP.NET. Low-level ASP.NET 5 focused bootstrap projects that both Orchard and any other ASP.NET project could be built on.

When Orchard was originally released my company loved the architectural patterns and ability to create vertical slices of features with modules. The extensibility was important for us to be able to offer product customization to 100's of customers without ending up in code branching hell by duplicating the source.

The catch was that we didn't need any of the content management functionality or the database access or even the more advanced extension points such as shapes. We ended up just stripping out everything we didn't need and using just the modularity, localization, logging etc. Maybe others would see a lot of value in bootstrapping their project without rolling their own modularity or branching the Orchard framework.

The approach seems to be inline with vNext providing just a small core of fundamental building blocks and anything else optionally being provided via NuGet. I agree with the approach @bleroy took in DecentCMS.

Happy to help with this if it's a direction the Orchard team wants to go.

**Comment by Jetski5822** [comment]
So the idea is to break up the Orchard.Framework project as an example in to its constituent parts, with specific vendor modules pushed in to their own namespaces. These would then be pushed and versioned to myget - which is the same workflow as the MVC team.

The core bundle will also contain a host, and probably a nuget package called OrchardVNext which will have reference to the abstracted out packages. The only thing I havent got my head around as of yet is how to turn on the default implementations....

However... the design is....

OrchardVNext.Web (Host)
OrchardVNext (Framework -  think this will need to be renames TBH)

OrchardVNext.DependencyInjection (Abstraction of the core DI)
OrchardVNext.DependencyInjection.Autofac (Vendor specific)

OrchardVNext.Routing (Abstracted out routing pattern)

OrchardVNext.Mvc (Abstracted out MVC pattern) - The idea here is that Orchard host shouldnt care about MVC
OrchardVNext.Mvc.Razor
There will probably be a shapes or templating one somewhere, but I have not got that far.

OrchardVNext.Data
OrchardVNext.Data.EF
OrchardVNext.Data.Dapper
Note: Only one will be bundled, however the concept is that you should be able to swap out the implementation of IContentStore and IContentQueryStore (nb: change to IQueryStore). I am also not saying we support both, more a PoC as I would prefer to use Dapper if anything.

The way I would like to head is that Orchard that you pull off the shelf has everything it needs opted in, just like today, however, if you want to build something else, and really like parts of orchard like the DI, well you can use that and not have to opt in to the routing system.

The other aspect I see is that the upgrade path for people will be much nicer. Today we have to do a big release of core and everyone gets everything. Going this route would allow us to say, hey, the dependency injection nuget package is upgraded so just update that and not the MVC package because at the moment I don't care about the MVC upgrade.

What's your thoughts?

**Comment by IntranetFactory** [comment]
I really like the idea to isolate Orchard modules into independent repositories. This would make our work a lot easier. I don't like the idea use nuget at all - I'd prefer to have the sources of the used modules merged and not just some binaries. So instead of nuget I'd suggest to use npm

**Comment by bleroy** [comment]
No no no no no. I don't think we're talking about separate repos. We used to do that, and it was a nightmare to manage. We walked away from it for a reason. It's horrible for the core team, and it's worse for users. What we're talking about, if I'm not mistaken, is to split things into less coupled packages, but we would still deliver default packages as part of the core Orchard solution and repo.

Another thing: I vote against "OrchardVNext", because that's going to cause lots of headaches when it's no longer vnext, and becomes vcurrent. Just call it "Orchard".

**Comment by sfmskywalker** [comment]
I am totally for the idea of having decoupled packages which other ASP.NET applications could take advantage of. It seems to deliver what was promised when Orchard was just conceived: to create reusable components that other ASP.NET apps could consume. Even if not used as such, striving for this enforces proper decoupled design. In order for things to remain practical, we'd have default packages as Bertrand mentioned.

Please drop the `OrchardVNext` term in the actual code and simply call it `Orchard`.

Great stuff.

**Comment by Jetski5822** [comment]
Separate repos = no, and never ever ever again! Like Taylor Swift said!

We are talking about decoupled packages.

The VNext tag was because I had it in the main repo at one point and didn't know if it was going to get traction. I will drop.

**Comment by dcinzona** [comment]
I love this idea.  Using aspects of Orchard like DI in other projects would be excellent, especially if modularized and installed via Nuget.  This could also help with upgrading current code because we could just update the Nuget package and be done with it.

**Comment by jrestall** [comment]
Similar discussion is going on currently in the MVC project. 

We seem to have similar goals if you replace MVC with Orchard :smile: E.g. 

> Add**Orchard**Core() is an advanced experience that gives an application developer fine-grained control over what features are provided by the **Orchard Framework** - you can mix and match dependencies with 3rd party frameworks, or avoid dependencies altogether that aren't needed.

https://github.com/aspnet/Mvc/issues/2872

Since we are brainstorming, I'll just put this here:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services
        .AddOrchardCore()
        .AddRouting()
        .AddShapes()
        .AddCaching()
        .AddContentManagement();
}
```

Though maybe we want something more dynamic if we are to collapse the 3 types of modules (framework/core/modules) into one type.

**Comment by bleroy** [comment]
Yes, much more dynamic: this won't scale as that interface would pretty much write the set of services in stone. It needs to be a dynamic discovery process that uses discovery providers that can discover services, and then configuration providers that can give them configuration. Pretty much like what we have today. I don't think that's the part that needs improving. What needs improving is decoupling of the services themselves.

**Comment by Jetski5822** [comment]
Yes, the discovery process at the moment is actually quite nice, though your idea could be done using extension methods later on within the individual packages, i.e. reference the package, then you have access to AddContentManagement() for example.

At the moment, the discovery will stay as is, using markers and configuration providers. The hard part is decoupling the services. I have pushed some code to master with moves a few things out of the framework. 

The three big areas that need moving out at the moment, at Data, DI, and Content Management. Once they are done, the rest will flow.

**Comment by bleroy** [comment]
Extension methods? I really don't see the point. Seems to me like this is insisting on expressing configuration through code. While that sort of thing makes some sense in more expressive and dynamic languages such as Ruby, it seems like a mismatch for C# to me.

**Comment by Piedone** [comment]
Again, why do we want this? The different framework-level features in Orchard.Framework (like logging, DI, data access, localization) are already suitably decoupled (if something is missing or suboptimal there, that can be directly fixed) and if you want to hand-pick what you want to use, you can. As mentioned above in several projects we do this with Orchard App Host (in desktop apps, cloud workers, Windows services and even non-Orchard web apps), in practice (and this is the only, slightly related issue: https://github.com/OrchardCMS/Orchard/issues/4748).

I can't see any practical disadvantage having all the pieces of the framework in the Orchard.Framework class library (if this is what we're mainly talking here) because it just doesn't bother you. A good framework is one where you have everything you need all the time but nothing is forced onto you: I think Orchard.Framework is mostly like this already.

**Comment by bleroy** [comment]
It seems like we're running in circles. It's not practical today to include parts of Orchard into an existing application, for example. This will help with that sort of scenario. Generally speaking, decoupling is good, and there is a lot of coupling in Fx that is not obvious until you hit it. I don't think this is about where we draw package lines, but a lot more about sane development practices. I think the real question is why would we not want this? Would a round of nDepend on the current dll convince you?

**Comment by Piedone** [comment]
"It's not practical today to include parts of Orchard into an existing application, for example." As mentioned, this is exactly what we do today in several projects of ours and it works without major issues. It would entertain me to see an nDepend diagram of the Framework but it just doesn't matter in my experience; in theory de-coupling is good and I like it, but I doubt it would bring any practical advantages here, but cause unnecessary complexity with the introduction of new abstractions, see below.

There are several places where Orchard is "opinionated" but I know only about a handful of cases (opened issues about all of them; can't recall all but one of them is that OrchardStarter does a lot of registrations that you not always need and thus it's most of the time just more feasible not to use it but to copy and modify it, which is less than ideal). I don't know about fundamental, structural issues but about very specific ones related to the framework developer only thinking about using Orchard.Framework in the context of Orchard.Web (which is an issue only slightly related to the packaging question here). However neither of these prevent you from utilizing parts of Orchard.Framework readily, without having to worry about its other parts, as my living, production, continuously developed, practical examples show. I don't worry about Orchard.Framework (and also sometimes non-Core modules or 3rd party modules) being usable in a selective manner in various projects they were never intended to be used in because I already do it :-). It would help if @jrestall could explain why exactly in their case they felt the need to strip out what they didn't need because this was never an issue for us.

I feel that we talk a lot of theory here and nobody really looks into the practical usability of somehow separating parts of the Framework more than how they are today. We shouldn't forget that Orchard.Framework is **Orchard**.Framework: most of it can't be made meaningful alone or more than a couple of helpers without running an Orchard shell. And once you run an Orchard shell there's nothing to my knowledge that you have to use if you don't want to. The code is there in Orchard.Framework for localization for example even if you don't use it in your app but does this have any meaningful impact?

Now what does have an impact on Orchard's usability as a generic framework is its dependency on System.Web. This is something very deep and scattered. However even this big and bad dependency (that I wholeheartedly would love to see go) only causes two issues: you can only run Orchard with the desktop CLR (though running Orchard as the core of a mobile app or on a Raspberry Pi is probably too far-fetched any way, but would be kind of cool) and you have to add a reference to System.Web (though you don't have to do anything more) if you make use of any type referencing any other type from System.Web (e.g. even if you want to use Localization you have to reference System.Web from your project since `LocalizedString` implements `IHtmlString`). I suppose with the move to ASP.NET 5 this is solvable in a way.

And a bonus question: isn't Framework features (like module features) that can be toggled on or off (regarding getting registered with Autofac and running on shell and other events) what you all really want? I can see a benefit in e.g. not loading the content management stuff on shell start if you don't want to use it. However this doesn't look like a big opportunity for performance gains (and I don't really see any other gains): just tried, and starting an Orchard framework and shell alone (with a single module loaded) is <2s and using <20MB of memory on my machine in Debug and from an HDD. Could be better of course, but maybe this is not something where efforts should be focused (though if anyone does it I'd be glad to test it).

**Comment by bleroy** [comment]
The tie to the desktop CLR is unfortunate, not because of the Raspberry Pi (I really don't care about that at all), but because of Linux, OSX, and .NET Native. The latter in particular could bring very significant wins in terms of scalability, memory footprint, and raw perf. This is not for right now, but definitely something to think about and prepare for.
I think it's great that you've been able to implement lots of cool stuff on .Nest, but that doesn't mean that others are pulling stuff out of their arses. In particular, there are parts of the Decent core that I'm working on isolating, in order to enable their usage outside of the CMS. I have very good reasons for that, thank you for asking (people asking for it for their own very real apps). Those parts are the dependency injection library (done), the multi-tenancy (working on it), localization (not started), and the querying engine. It won't be too hard, because I had that in mind from the start.
In the end, I don't want to impose what anyone works on, we all get to choose what we find interesting. If Nick finds this interesting, he should go for it. You think it's not worth his time, I think it is. Well, he's the judge in the end: it's his time. The question of whether we should take that contribution once it exists is distinct, but I think we did already agree that less coupling is good, so it seems like this one is settled.

Peace.

**Comment by Jetski5822** [comment]
The CoreCLR compliance is one of the key factors to moving to asp.net vnext. Allowing you to run on Linux, OSX, or whatever the CoreCLR platform supports is totally the way to go.

Orchard Framework in my opinion has turns in to a massive opt in modal. Which works for some people and not others. Some people dont want to use MVC, but like other aspects of Orchard but at the moment they would have to split the MVC stuff out, this is a headache as everything is kind of tied together making separating it out difficult - try it, I am trying it now, and it is a slow process.

**Comment by Jetski5822** [comment]
This work is loosly done. It is an ongoing piece of work, but most is split out. There is still a sizable chunk of framework not ported over, but this task was for what was there not for what was in Framework currently.
