### ISSUE TITLE
Question on using EF and IdentityFramework

### ISSUE THREAD

**Issue by omidkrad** [OrchardCMS/Brochard#22]
Hi, I was wondering if you are planning to use [Entity Framework](http://www.asp.net/entity-framework) and ASP.NET [Identity Framework](http://www.asp.net/identity) for this vNext Orchard? In the original Orchard there was no easy way to convert an existing website to an Orchard site. I at least expected that there was a module that could wrap an existing website and enable it as a feature that could be displayed in the Orchard site. I want to suggest to have this in mind when designing Brochard. Use of Identity Framework especially will make it straightforward to bring existing Users and Roles from an existing web project, and keep it compatible with existing [Identity Manager](https://github.com/IdentityManager/IdentityManager/wiki)s that implement Id Framework interfaces.

Thanks!

**Comment by Jetski5822** [comment]
At the moment EF is used because it contains CoreCLR support, but the way it will b e abstracted off will allow you to implement other content stores through other orms or whatever,

I have not looked at the identity provider stuff, that will come when we look at redesigning the Orchard.Users and Orchard.Roles modules.
